name: Build and Push Image

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    if: startsWith(github.event.release.tag_name, 'CLI') == false
    env:
      NODE_OPTIONS: --max-old-space-size=4096

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }
      - name: Use Node.js ${{ matrix.node-version }}

        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0

      - run: yarn workspaces foreach -A install

      - run: yarn lint --since origin/main

      - run: yarn tsc
        continue-on-error: true

      - run: yarn workspaces foreach -W --include 'plugins/**' run build

      - run: yarn tsc

      - run: yarn test

      - run: yarn build:backend

      - id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/terasky-oss/kubestage
          tags: type=sha,format=long
      
      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build-and-push
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      
      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
