name: CLI Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write # Needed for sigstore keyless signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Run GoReleaser
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign the artifacts
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          for artifact in dist/backstage-config-generator_*; do
            if [[ -f "$artifact" && -x "$artifact" ]]; then
              cosign sign-blob --yes "$artifact" > "${artifact}.sig"
              cosign verify-blob --yes "$artifact" --signature "${artifact}.sig"
            fi
          done

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: dist/
          format: spdx-json
          artifact-name: sbom.spdx.json

      - name: Sign SBOM
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign-blob --yes sbom.spdx.json > sbom.spdx.json.sig
          cosign verify-blob --yes sbom.spdx.json --signature sbom.spdx.json.sig