name: NodeJS CI And Plugin Publishing

on:
  push:
    tags:
      - '*'
      - '!CLI-*'

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    env:
      NODE_OPTIONS: --max-old-space-size=4096
      NPM_CONFIG_PROVENANCE: true
      
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@terasky'

      - run: yarn workspaces foreach -A install
      - run: yarn lint --since origin/main
      - run: yarn tsc
        continue-on-error: true
      - run: yarn workspaces foreach -W --include 'plugins/**' run build
      - run: yarn tsc
      - run: yarn test
      - run: yarn build
      - run: ./publish.sh
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Generate release notes
        run: |
          ./hack/generate-version-table.sh > RELEASE_NOTES.md
          sed -i 's/RELEASE_VERSION/v${GITHUB_REF#refs/tags/}/g' RELEASE_NOTES.md
      - name: Create GitHub Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: RELEASE_NOTES.md
